### ISSUE TITLE
Epic: MVP

### ISSUE THREAD

**Issue by yosriady** [comit-network/app#38]
> [Original](https://3.basecamp.com/4403044/buckets/16118740/messages/2551580069)

**MVP Feature Set Progress**

- [ ] Users can install and run the desktop app on their machines: MacOs, Linux and Windows (Electron provides these out of the box).
  - [ ] Fix Electron release pipeline https://github.com/comit-network/app/issues/19
  - [ ] Testnet / mainnet nodes required to package the app https://github.com/comit-network/app/issues/37
  - [ ] Maker backend needs to be hosted somewhere https://github.com/comit-network/app/issues/20
- [x] Users can swap DAI for BTC (and vice versa.)
  - [ ] Partially blocked by open issue with bitcoin balances being stale / inconsistent https://github.com/comit-network/comit-js-sdk/issues/177
- [ ] Users can track and step through swaps for the redeem & refund path. (Currently active)
   - [ ] Progress tracking UI https://github.com/comit-network/app/issues/21
   - [ ] Extend state machine with branching support https://github.com/comit-network/app/issues/18
   - [ ] Implement Refund and Expiry flow https://github.com/comit-network/app/issues/18
- [x] Users can view their wallet balances.
  - [ ] More client-side balance validation https://github.com/comit-network/app/issues/17
- [ ] Users can use an external wallet (Ledger) for their Bitcoin and Ethereum wallets.
- [x] Users can view a list of current and past swaps.
    - [ ] Refactor retrieving swaps to follow canonical way https://github.com/comit-network/app/issues/34
- [x] Users can view the exchange rate (of the single maker.)
  - [ ] Rates should be refreshable https://github.com/comit-network/app/issues/25

**Comment by yosriady** [comment]
Moved to https://github.com/coblox/admin/issues/206
