### ISSUE TITLE
Epic: Decentralized Orderbook

### ISSUE THREAD

**Issue by yosriady** [comit-network/app#42]
**Pitch**
https://3.basecamp.com/4403044/buckets/16930224/messages/2632331598

**TODOs**

- [ ] Upgrade SDK https://github.com/comit-network/app/issues/39
- [ ] Refund Redeem flow https://github.com/comit-network/app/issues/18
- [ ] Swap Progress UI https://github.com/comit-network/app/issues/21
