### ISSUE TITLE
Maker Backend & Taker Frontend: Implement swaps

### ISSUE THREAD

**Issue by yosriady** [comit-network/app#5]
> [Technical specs](https://github.com/coblox/product-squad/wiki/COMIT-Product-Technical-Specification)

The Node.js backend API is responsible for making BTC-DAI offers for the user and proceed with the swap if someone takes the offer from the desktop client.

This task implements:
- Running a Bitcoin and Ethereum node as the maker, using the SDK (?)
- Accepts swap requests
- Executes swap requests

I'm not yet clear of which of the functionality is already implemented by the SDK and which needs to be implemented.

**Definition of Done**
- Users can submit a swap request to the maker.
- Users can perform a swap with the maker (to be expanded.)

<details>
  <summary>Phase 1</summary>
  

**TODOs**
- [x] Evaluate browser wallet integration / walletconnect
  - [ ] ~~Grok `EthereumWallet` SDK interface under the hood to evaluate integration with Ledger / other wallets~~ Halting wallet integration
  - [ ] ~~Research injecting providers for ledger support https://github.com/MetaMask/web3-provider-engine~~ Extracted to issue
- [x] Go through https://comit.network/docs/getting-started/create-comit-app/
- [ ] Set up infra for maker backend
   - [ ] ~~Run Bitcoin and Ethereum nodes for the service (locally)~~ Halting node setup
      - [ ] Go through https://github.com/comit-network/create-comit-app/tree/master/scripts to run nodes locally (separate pairs) for maker backend and for desktop app
        - [x] Set up https://en.bitcoin.it/wiki/Bitcoind
            - [x] https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md
                 - `./src/bitcoind` / `./src/bitcoin-cli stop`
            - [x] Grok `InMemoryBitcoinWallet` config parameters https://github.com/bcoin-org/bcoin/blob/master/docs/README.md
             - [x] https://medium.com/@bitstein/setting-up-a-bitcoin-lightning-network-test-environment-ab967167594a
             - [x] Clarify about 'regtest` network and what it affects
             - [ ] Grok https://github.com/bitcoin/bitcoin/blob/master/share/examples/bitcoin.conf
                  - rpc settings
             - [x] Create bitcoin.conf with the following config https://github.com/comit-network/create-comit-app/blob/master/scripts/src/docker/bitcoin.rs#L52-L62
        - [ ] Set up Ganache locally for Ethereum (URI, private key, erc20 contract address)
        - [ ] Set up `cnd` locally
        - [ ] configure `.env` in its proper directory under `maker/`
   - [ ] ~~Evaluate hosted services for nodes e.g. https://alchemyapi.io/infrastructure~~ Extracted to issue
   - [ ] Config environment variables
    - ~~`~/.create-comit-app/env` is bad DX, is there a way to configure where the env should live? Right now, developers cannot use `comit-scripts` for anything other than running the example.~~ Not meant for actual use
   - [ ] ~~Once Bitcoin and Ethereum infra is set up,~~ Proceeding with local nodes from `comit-scripts`, see below spec
</details>

**TODOs Phase 2**
- [x] Maker Backend
    - [x] Initialize Maker
    - [x] Create endpoint `GET /` (root) to display maker info e.g. `peerId`, `addresshint` for Frontend Taker to use to `createSwap`
    - [x] Create endpoint `GET /swaps` to return `maker.comitClient.getNewSwaps()`
    - [x] Grok Swap fetch function https://github.com/comit-network/comit-js-sdk/blob/9ab87203d0c204ea24c32312b1d485e4f4cea975/src/cnd/cnd.ts#L161
   - [x] State machine for Maker to do 'next' step when polling
   - [x] Spike and implement polling mechanism
    - [x] Needs to poll for `taker.comitClient.sendSwap` to be confirmed, and
    - [x] call `makerSwapHandle.accept(...)`
    - [x] Needs to poll for `takerSwapHandle.fund(...)` to be confirmed, and
    - [x] call `makerSwapHandle.fund(...)`
   - [x] Needs to poll for `takerSwapHandle.redeem(...)` to be confirmed, and call:
   - [x] `makerSwapHandle.redeem`
- [x] Taker Frontend
   - [x] Initialize Taker
   - [x] `SwapForm` submit should `createSwap` and,
   - [ ] ~~(Optional) Implement a confirmation [modal](https://rimble.consensys.design/templates/tx-summary)~~
   - [x] `sendSwap`
   - [x] Implement `SwapList` component for `HomePage`
   - [x] Implement `SwapDetailsPage` to display status and info of a single swap and perform next steps
      - Automated with `useEffect`? Or manual / user-initiated?
   - [x] State machine for Taker to do 'next' step when polling
   - [x] Spike and implement polling mechanism
    - [x] Needs to poll for `makerSwapHandle.accept(...)` to be confirmed, and call:
   - [x] `takerSwapHandle.deploy(...)`
   - [x] `takerSwapHandle.fund(...)`
   - [x] Needs to poll for `makerSwapHandle.fund(...)` to be confirmed, and call:
   - [x] `takerSwapHandle.redeem`
   - [x] Needs to poll for `makerSwapHandle.redeem(...)` to be confirmed, and:
   - [x] let user know that the swap is done
- [ ] ~~Debug bitcoin balances not displaying correctly~~ Split into separate issue
- [x] Update README to describe architecture and setup instructions (Maker & poller, Taker, etc.)
- [x] Final round of cleanup and refactoring beforge merging to `master`
  - [ ] ~~Taker: Refactor MAKER_URL to application-level .env~~ Deferred to separate issue
  - [ ] ~~Refactor taker & maker state machines into its own class with data + functions~~ Deferred to separate issue
     - `runTakerNextStep` and `parseTakerSwapStatus`
  - [x] Address all remaining inline TODOs

Open Questions
- [ ] ~~Should the desktop app also have its own backend instead of having the app call the COMIT SDK?~~
  - especially for monitoring transactions?
- [ ] ~~Monitoring maker & taker confirmations~~ Swap.fetchDetails returns status for: swap, alpha & beta ledgers, communication
  - [ ] ~~Implement or use a third-party service e.g. AlchemyAPI~~
  - [ ] ~~SDK may need to return transaction ID on functions that perform a transaction, for async monitoring purposes~~ Available in `Swap` object

**Comment by D4nte** [comment]
> - Running a Bitcoin and Ethereum node as the maker, using the SDK **(?)**

Hi @yosriady, just to be sure we are on the same page. We prefer that you tell us (or you open PRs) to update the SDK so it's usable than not using the SDK 🙂

**Comment by yosriady** [comment]
@D4nte 

Are developers supposed to use `comit-scripts` to manage their production nodes? Since it was part of `create-comit-app` and not `comit-sdk`, I thought it was more for running a development environment to run the examples.

For a production-ready setup, wouldn't developers need to run their own nodes? Maybe I'm missing something here. I don't see how you can run a Bitcoin and Ethereum node using the SDK. 🤔

**Comment by bonomat** [comment]
Really good question: `comit-script` should just help to spin up a developer environment and the `comit-sdk` does not concern the environment at all. 

For a production-ready setup a developer would need to provide their own nodes.
